name: Sync and Create Rebase PR

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly at midnight UTC on Sunday

permissions:
  contents: write
  actions: write
  pull-requests: write

env:
    GH_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}

jobs:
  sync-and-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Cache git folder
        uses: actions/cache@v4
        with:
          path: .git
          key: git-folder

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          ref: deploy
          fetch-depth: 0 # Get full history for rebasing

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        continue-on-error: true
        run: git remote add upstream https://github.com/NixOS/nixpkgs.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Rebase onto updated nixos-unstable
        run: |
          git rebase upstream/nixos-unstable
          git push -f origin HEAD

      - name: Trigger flake.lock update
        run: |
          gh api -X POST /repos/xinyangli/nixos-config/dispatches -f event_type='flake_bump'
